server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dummydb
    username: postgres
    password: 
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

logging:
  level:
    com.yourpackage: DEBUG
    org.hibernate.SQL: DEBUG

feign:
  client:
    config:
      default:
        loggerLevel: full
